name: xbox_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:

  assets:
    - assets/error.webp
 
  
  
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: Xbox
      fonts:
        - asset: fonts/xbox360.ttf 
    - family: SegoePro
      fonts:

        - asset: fonts/SegoePro-Light.ttf
          weight: 200          
        - asset: fonts/SegoePro-Semilight.ttf        
          weight: 300         
        - asset: fonts/SegoePro-Regular.ttf
          weight: 400  
        - asset: fonts/SegoePro-Semibold.ttf
          weight: 600
        - asset: fonts/SegoePro-Bold.ttf
          weight: 700       
        - asset: fonts/SegoePro-Black.ttf
          weight: 900

       
        - asset: fonts/SegoePro-LightItalic.ttf
          weight: 200   
          style: italic       
        - asset: fonts/SegoePro-SemilightItalic.ttf        
          weight: 300         
          style: italic 
        - asset: fonts/SegoePro-SemiboldItalic.ttf
          weight: 600
          style: italic       
        - asset: fonts/SegoePro-BoldItalic.ttf
          weight: 700       
          style: italic       
        - asset: fonts/SegoePro-BlackItalic.ttf
          weight: 900
          style: italic       



 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
